//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exer2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Animal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animal()
        {
            this.Item_Agendado = new HashSet<Item_Agendado>();
        }
    
        public int ID_Animal { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DT_Nasc { get; set; }
        [Required]
        [StringLength(100)]
        public string Nome_Animal { get; set; }
        [Required]
        [StringLength(1, ErrorMessage = "Apenas a primeira letra.")]
        public string Castrado { get; set; }
        [StringLength(1, ErrorMessage = "Apenas a primeira letra.")]
        public string Pelagem { get; set; }
        public Nullable<int> COD_RGA { get; set; }
        public Nullable<int> Micro_Chip { get; set; }
        [StringLength(1, ErrorMessage = "Apenas a primeira letra.")]
        public string Sexo { get; set; }
        [StringLength(100)]
        public string Especificação { get; set; }
        public Nullable<int> ID_Tipo { get; set; }
        public Nullable<int> ID_Porte { get; set; }
        public Nullable<int> ID_Municipe { get; set; }
        public Nullable<int> ID_Especie { get; set; }
        public Nullable<int> ID_Cor { get; set; }
        
        public virtual Cor Cor { get; set; }
        public virtual Especie Especie { get; set; }
        public virtual Especie Especie1 { get; set; }
        public virtual Municipe Municipe { get; set; }
        public virtual porte porte { get; set; }
        public virtual Tipo Tipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_Agendado> Item_Agendado { get; set; }
    }
}
