//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exer2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CEPAD_IIIEntities : DbContext
    {
        public CEPAD_IIIEntities()
            : base("name=CEPAD_IIIEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrador> Administradors { get; set; }
        public virtual DbSet<Agendum> Agenda { get; set; }
        public virtual DbSet<Animal> Animals { get; set; }
        public virtual DbSet<Cor> Cors { get; set; }
        public virtual DbSet<Disp_Atend> Disp_Atend { get; set; }
        public virtual DbSet<Especie> Especies { get; set; }
        public virtual DbSet<Item_Agendado> Item_Agendado { get; set; }
        public virtual DbSet<Municipe> Municipes { get; set; }
        public virtual DbSet<porte> portes { get; set; }
        public virtual DbSet<Tipo> Tipoes { get; set; }
        public virtual DbSet<Tipo_Atendimento> Tipo_Atendimento { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
