//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exer2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CEPAD_IIIEntities : DbContext
    {
        public CEPAD_IIIEntities()
            : base("name=CEPAD_IIIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrador> Administrador { get; set; }
        public virtual DbSet<Agenda> Agenda { get; set; }
        public virtual DbSet<Animal> Animal { get; set; }
        public virtual DbSet<Cor> Cor { get; set; }
        public virtual DbSet<Disp_Atend> Disp_Atend { get; set; }
        public virtual DbSet<Especie> Especie { get; set; }
        public virtual DbSet<Item_Agendado> Item_Agendado { get; set; }
        public virtual DbSet<Municipe> Municipe { get; set; }
        public virtual DbSet<porte> porte { get; set; }
        public virtual DbSet<Tipo> Tipo { get; set; }
        public virtual DbSet<Tipo_Atendimento> Tipo_Atendimento { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
