//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exer2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agenda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agenda()
        {
            this.Item_Agendado = new HashSet<Item_Agendado>();
        }
    
        public int ID_Agenda { get; set; }
        public Nullable<int> ID_Especie { get; set; }
        public Nullable<int> ID_TA { get; set; }
        public Nullable<int> ID_Porte { get; set; }
        public Nullable<int> ID_Usuario { get; set; }
    
        public virtual Especie Especie { get; set; }
        public virtual porte porte { get; set; }
        public virtual Tipo_Atendimento Tipo_Atendimento { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_Agendado> Item_Agendado { get; set; }
    }
}
