//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exer2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class Disp_Atend
    {
        [DisplayName("Data inicial")]
        public System.DateTime DT_Inicio { get; set; }
        [DisplayName("Data final")]
        public System.DateTime DT_Fim { get; set; }
        
        public Nullable<int> NT_Atend_Ofer { get; set; }
        [DisplayName("Quantidade de atendimento")]
        public Nullable<int> Num_Atend_Agendado { get; set; }

        public Nullable<int> ID_TA { get; set; }
        [DisplayName("Porte")]
        public Nullable<int> ID_Porte { get; set; }
        [DisplayName("Tipo")]
        public Nullable<int> ID_Tipo { get; set; }
    
        public virtual porte porte { get; set; }
        public virtual porte porte1 { get; set; }
        public virtual Tipo_Atendimento Tipo_Atendimento { get; set; }
        public virtual Tipo_Atendimento Tipo_Atendimento1 { get; set; }
        public virtual Tipo Tipo { get; set; }
        public virtual Tipo Tipo1 { get; set; }
    }
}
