//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exer2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Agendado
    {
        public int ID_Protocolo { get; set; }
        public Nullable<int> ID_Agenda { get; set; }
        public Nullable<int> ID_Animal { get; set; }
    
        public virtual Agenda Agenda { get; set; }
        public virtual Animal Animal { get; set; }
    }
}
