//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exer2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Municipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Municipe()
        {
            this.Animal = new HashSet<Animal>();
        }
    
        public int ID_Municipe { get; set; }
        public string Nome { get; set; }
        public Nullable<int> RG { get; set; }
        public Nullable<System.DateTime> DT_Nasc { get; set; }
        public Nullable<int> Tel_Fixo { get; set; }
        public string UF { get; set; }
        public string Rua { get; set; }
        public Nullable<int> NR_Casa { get; set; }
        public string Bairro { get; set; }
        public Nullable<int> Celular { get; set; }
        public string CPF { get; set; }
        public Nullable<int> ID_Usuario { get; set; }
        public string Email { get; set; }
        public string Cidade { get; set; }
        public string Complemento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animal> Animal { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
