//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exer2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrador
    {
        public int ID_Adm { get; set; }
        public Nullable<int> RM { get; set; }
        public string Cargo { get; set; }
        public Nullable<int> ID_Usuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
